module.exports = {
  _id: 1,
  "local.email": 1,
  "local.password": 1,
  "facebook.id": 1,
  "twitter.id": 1,
  "google.id": 1,
  // info: 1,
  "info.avatar": 1,
  "info.username": 1,
  "info.name": 1,
  "info.lastName": 1,
  "info.phone": 1,
  "info.website": 1,
  "info.bio": 1,
  "info.sex": 1,
  posts: 1,
  // totalPosts: 1,
  taggedPosts: 1,
  archivedPosts: 1,
  collections: 1,
  following: 1,
  // totalFollowing: 1,
  followers: 1,
  // totalFollowers: 1
}
